version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    #environment:
     # WORDPRESS_DB_HOST: db
     # WORDPRESS_DB_USER: root
     # WORDPRESS_DB_PASSWORD: 1234
     # WORDPRESS_DB_NAME: test
    env_file: .env 
    volumes:
      - wordpress:/var/www/html
    networks:
      - mybridge

  db:
    image: mariadb:10.6.0-focal
    restart: always
    #environment:
      #MYSQL_DATABASE: test
      #MYSQL_USER: "${MARIADB_USER}"
      #MA_PASSWORD: "${MARIADB_PASSWORD}"
      #MARIADB_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - mybridge
volumes:
  wordpress:
  db:
networks:
  mybridge:
